### PR TITLE
Feature/v2.10

### LINKED ISSUE #59: New version Swiss ephermeris code
Hello Ralf.

Here is the code of 2.09.03: https://www.astro.com/ftp/swisseph/
and
https://www.astro.com/ftp/swisseph/src/

There are two new functions to include in the R code:
swe_houses_ex2() and
swe_houses_armc_ex2().
We propose to remove the functions that provide lesser output:  swe_houses_ex() and swe_houses_armc()

Let me know when you have time, as I need to replace these two old ones with new ones.

All the best and stay healthy.

Victor

----
Last comment on this version:

Hi,

this release has three minor bug fixes:

- An initialization *serr = '\0'; was missing in function swe_calc(), which could lead to crashes when error messages were written.

- Sidereal positions of asteroids were wrong with ayanamshas 9-16, 21-26, 37, 38, 41, 42. (Namely, all ayanamshas whose initial date is given in UT.)

- Asteroids with ipl > 10000 (SE_AST_OFFSET): calculating with several different ayanamshas after each other did not work properly.

The first bug was intoduced with version 2.09.01.
The 2nd one exists since version 2.05, this is 5 years old.
The 3rd one exists since more than 20 years. It seems that either sidereal astrologers rarely use asteroids or they rarely use the above-mentioned ayanamshas.

Best wishes,

Dieter

### PR DESCRIPTION
**Pull request by rstub**
fixes #59

### CODE REVIEW

**Comment by rstub** [comment]
@vreijs Version 2.10.03 introduces some changes in the tests:

```
✖ | 5      58 | Eclipses and planetary phenomena [0.4s]                                                      
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-eclipse_pheno.R:77): Finds the next occultation for a body and a given geographic position.
result$attr[1:9] not equal to c(...).
4/9 mismatches (average diff: 0.173)
[1]    45.1 -    45.1 ==  0.00147
[2]   101.9 -   101.9 ==  0.00337
[3] 10375.3 - 10374.6 ==  0.68573
[4] -3451.9 - -3451.9 == -0.00113

Failure (test-eclipse_pheno.R:97): Compute the geographic location of an occultation for a given tjd.
result$attr[1:9] not equal to c(...).
4/9 mismatches (average diff: 0.103)
[1]    39.6 -    39.6 ==  0.00129
[2]    78.3 -    78.3 ==  0.00259
[3]  6127.3 -  6126.9 ==  0.40497
[4] -3444.5 - -3444.5 == -0.00147

Failure (test-eclipse_pheno.R:108): Lunar eclipse at a certain location
result$attr[1:11] not equal to c(...).
7/11 mismatches (average diff: 4.93e-05)
[1]   0.718 -   0.718 ==  8.18e-06
[2]   1.746 -   1.746 ==  8.19e-06
[5] 240.643 - 240.643 == -1.36e-04
[6]  -0.351 -  -0.351 == -9.83e-05
[7]   0.186 -   0.186 == -8.20e-05
[8]   0.587 -   0.587 == -4.27e-06
[9]   0.718 -   0.718 ==  8.18e-06

Failure (test-eclipse_pheno.R:134): Phenomena of Moon (UT)
result$attr[1:6] not equal to c(...).
3/6 mismatches (average diff: 0.0135)
[3] 30.294 - 30.294 ==  1.52e-08
[4]  0.518 -  0.518 == -1.94e-04
[5] -6.783 - -6.824 ==  4.03e-02

Failure (test-eclipse_pheno.R:142): Phenomena of Moon (ET)
result$attr[1:6] not equal to c(...).
2/6 mismatches (average diff: 0.0963)
[4]  0.52 -  0.521 == -0.000195
[5] -6.27 - -6.466 ==  0.192406
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ | 2      94 | Misc tests [0.2s]                                                                            
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-misc.R:84): Determing ayanamsa using UT:
result$return not equal to 68.
1/1 mismatches
[1] 4 - 68 == -64

Failure (test-misc.R:92): Determing ayanamsa using ET:
result$return not equal to 68.
1/1 mismatches
[1] 4 - 68 == -64
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Do you know if these changes make sense, i.e. I can simply update the values we are testing for?

**Comment by vreijs** [comment]
Hello Ralf, the difference in the eclipse related outputs seem ok. When
they made changes in this procedure, it will likely have some impact (all
is also quite small). So here I would update the testing function.

The ayanamsa seem to be more a different. I will need to put this to the
authors of SE. Give me some time. I will dig up the test-misc function
first.

All the best,

Vicor

**Comment by rstub** [comment]
fixes #62

**Comment by vreijs** [comment]
Hello Ralf,

As far as I can see, adjust the ayanamsa expected results to the new
results. They made osm echanges.

All the best,

Victor

**Pull request merged**
