### PR TITLE
Vreijs/section5

### PR DESCRIPTION
**Pull request by vreijs**

### CODE REVIEW

**Review by rstub — COMMENTED** [review]
Good catch. Could you also change the corresponding line in `README.Rmd`?

**Comment by rstub** [comment]
Is anything missing or can this be merged once v0.2.1 has been checked on CRAN?

**Comment by vreijs** [comment]
I think I updated the readme.rmd file (i though I could do this with knitr, but for some reason I needed to do it manually, but perhaps I forgot the workflow (i installed knitr).

**Comment by vreijs** [comment]
It can be merged. I don't want to add more at this very moment (missing 5 eclipse functions still, but I have not enough spare time to do that at this moment).

**Comment by rstub** [comment]
> I think I updated the readme.rmd file (i though I could do this with knitr, but for some reason I needed to do it manually, but perhaps I forgot the workflow (i installed knitr).

`README.Rmd` is the source from which `README.md` is generated. So in principle it is sufficient to edit `README.Rmd` and `knit` the result.

**Comment by vreijs** [comment]
Aha, I thought it the other way around, but now I understand why md was (again) changed when I had knited rmd;-)

**Comment by vreijs** [comment]
I hope I did the necessary steps to make this branch merge-able into master...

**Comment by vreijs** [comment]
Thanks hope all goes well with the whole process.

**Comment by rstub** [comment]
The ASAN errors found on CRAN are gone, so that is good. V0.2.1 has not been build on all platforms yet, but I do not expect any other problems. When I have time I will try to figure out why this wasn't caught in my tests and how to prevent this from happening in the future. It is quite likely that there are more such errors in the SE code we haven't exposed to R via tests or examples yet. Something like https://github.com/jeroenooms/curl/blob/master/docker/r-devel-san/Dockerfile mentioned in https://github.com/rocker-org/r-devel-san/issues/3 might be useful.

Let me know when you need another branch for the remaining eclipse functions. Although, I think you should be able to create one yourself:

* Go to the "git" tab in RStudio make sure that you are on `master` and up-to-date, i.e. do a `pull`
* Click the "New Branch" button and give it a descriptive name ("Remote" should be "origin", "Sync branch with remote" should be ticked)

After that  RStudio will switch to the new branch and each `push` and `pull` will be for that branch by default.

**Comment by vreijs** [comment]
Indeed a pity that it was not caught earlier. Would indeed be nice to have that include in future test! I will try myself to make a branch (handy for the future).

**Comment by vreijs** [comment]
Just made a new branch...

**Comment by rstub** [comment]
@f-silva-archaeo The functions from section 5 are implemented, but we won't make a new release until #52 is resolved. Meanwhile you can get the latest version via `drat`

```r
if (!requireNamespace("drat", quietly = TRUE)) install.packages("drat")
drat::addRepo("rstub")
install.packages("swephR")
```

or directly with `remotes::install_github("rstub/swephR")`.

**Pull request merged**
