### PR TITLE
Get it to work on MacOS

### PR DESCRIPTION
**Pull request by rstub**

### CODE REVIEW

**Comment by vreijs** [comment]
Hello Ralf, I see you are busy. I did in the mean time a few swe functions
(three eclipse ones, fixtar2 which seems not to work [discussing at the SE
e-group, and deltat_ex):
export(swe_azalt)
export(swe_calc)
export(swe_day_of_week)
export(swe_deltat)
export(swe_deltat_ex)
export(swe_fixstar)
export(swe_fixstar2)
export(swe_get_tid_acc)
export(swe_lun_eclipse_when)
export(swe_lun_eclipse_when_loc)
export(swe_rise_trans_true_hor)
export(swe_set_delta_t_userdef)
export(swe_set_ephe_path)
export(swe_set_tid_acc)
export(swe_set_topo)
export(swe_sol_eclipse_when_loc)
export(swe_version)

I am not using your simplified workflow yet, but will start working along
that soon, beside getting fixstar2 working (which should be more efficient
than fixstar).

All the best,


Victor

**Comment by vreijs** [comment]
Hello Ralf,

I if just have installed sewphR and then do 'Clean and Build' (in RStudio)
I get these compiling warnings:
"C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include"
-DNDEBUG
-I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3
-Wall  -std=gnu99 -mtune=generic -c libswe/swepcalc.c -o libswe/swepcalc.o
libswe/swepcalc.c: In function 'nacalc':
libswe/swepcalc.c:121:41: warning: 'rspeed' may be used uninitialized in
this function [-Wmaybe-uninitialized]
       if (pspe != NULL) pspe [planet] = swe_d2l (rspeed * DEG);
                                         ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include"
-DNDEBUG
-I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3
-Wall  -std=gnu99 -mtune=generic -c libswe/sweph.c -o libswe/sweph.o
libswe/sweph.c: In function 'swecalc':
libswe/sweph.c:4046:5: warning: 't' may be used uninitialized in this
function [-Wmaybe-uninitialized]
     swi_bias(xx, t, iflag, FALSE);
     ^
libswe/sweph.c:3913:10: note: 't' was declared here
   double t;
          ^
"
Should I mentioned them on the SE yahoo group? And do we have more
errors/warnings we need to communicate with that group?

Let me know. Thanks

**Comment by rstub** [comment]
Cool, I gave added a new issue #12 so we can keep track of which methods are still needed. As for the warning: Yes, these are the sort of things I got rid of in this branch for the `clang` compiler, which is used on MacOS. I think some of the warnings revealed actual bugs. Once I get around to subscribe to the SE mailing list I will start raising these points.

**Comment by vreijs** [comment]
Here are two more warnings while compiling (after an 'Install' of 'new' swephR package):
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -UNDEBUG -Wall -pedantic -g -Og -c libswe/swehouse.c -o libswe/swehouse.o
libswe/swehouse.c: In function 'sunshine_solution_makransky':
libswe/swehouse.c:2589:7: warning: 'r' may be used uninitialized in this function [-Wmaybe-uninitialized]
    cu = 180 + r;
       ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/VRHome/Documents/R/win-library/3.5/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -UNDEBUG -Wall -pedantic -g -Og -c libswe/sweph.c -o libswe/sweph.o
libswe/sweph.c: In function 'app_pos_etc_moon':
libswe/sweph.c:4046:5: warning: 't' may be used uninitialized in this function [-Wmaybe-uninitialized]
     swi_bias(xx, t, iflag, FALSE);
     ^

So up to now I got four different warnings. At this moment I am mentioning some inconsistencies in the manual of SE (swephprg) and still working on this fixstar2 issues with the authors.

**Pull request merged**
