### PR TITLE
Vreijs/documentation

### PR DESCRIPTION
**Pull request by vreijs**
I think I have included now items more consistent and made my first iteration of a vignette. Feedback is welcome.

### CODE REVIEW

**Comment by vreijs** [comment]
So I am getting through the 1st check (continuous-integration/appveyor/branch — AppVeyor build succeeded ), but then it fails. What do I  do wrong here?

P.S. This CI process indeed is very handy (and I removed due to that errors).

**Comment by vreijs** [comment]
It seems to work now (I just removed a typo in a comment)! It seems that runnign thingfs twice helps in this environment...

**Comment by rstub** [comment]
Sometimes there are random(?) hick-ups during the CI builds (networks not reachable ...). One typical symptom is e.g. one Linux build failing after just a few seconds.When I see that, I typically just restart that particular build. I am not sure If you are allowed to do that, too.

**Comment by vreijs** [comment]
What I did is change for instance one letter in a comment and then do a
commit again (that starts the process;-)

**Comment by rstub** [comment]
Can you add some test cases for the vectorized functions? Thanks.
 
BTW, would it make sense to drop the `vec_` prefix from these functions?

**Comment by vreijs** [comment]
Hello Ralf,

On Sat, 24 Nov 2018 at 11:04, Ralf Stubner <notifications@github.com> wrote:

> Can you add some test cases for the vectorized functions? Thanks.
>
I first wanted to know if the data definitions are ok and R-wise? I find
them somewhat cumbersome these list of lists. I was also thinking should I
use only a return-list (and not list 0f one list) when the max. input
vector length is one (but that will make the analysis of the results
depending on the length, so perhaps not that preferred). So some
(R-)guideance might be helpful for me.

> BTW, would it make sense to drop the vec_ prefix from these functions?
>

I think I indeed also asked that question. Initially I had done then, but
when doing the existing testthat, it ended in a loop (I think because it
was seeing e.g. calc_ut() as the new calc_ut() or the existing calc_ut().
So I must have the aliases(?)/environment(?)/scope(?) wrong?

Thanks for the feedback.

All the best,


Victor

>

**Comment by rstub** [comment]
> I first wanted to know if the data definitions are ok and R-wise? I find them somewhat cumbersome these list of lists. I was also thinking should I use only a return-list (and not list 0f one list) when the max. input vector length is one (but that will make the analysis of the results depending on the length, so perhaps not that preferred). So some (R-)guideance might be helpful for me.

Good point. I will try to find some time where I can actually look at these functions.

> I think I indeed also asked that question. Initially I had done then, but when doing the existing testthat, it ended in a loop (I think because it was seeing e.g. calc_ut() as the new calc_ut() or the existing calc_ut(). So I must have the aliases(?)/environment(?)/scope(?) wrong? Thanks for the feedback.

I probably missed your question. Sorry about that. The problem is that for swe_calc (and swe_fixstar2; also with _ut) we already use the function name without swe_. Normally the C++ functions use the name without `swe_` but get renamed to the name with `swe_` at the R level. This way we have the normal names at the R level but do not interfere with the existing C functions in the C++ files. However, for `calc` and `fixstar2` we do not rename the functions for the R level but also do not export these functions. Instead we have our own wrapper R functions named `swe_calc` etc., which are used to add some vectorization. I am not sure how to solve this best ...

BTW, what is the difference between the  vectorization offered in `swe_calc` et al. compared to the one in `vec_calc`?

**Comment by vreijs** [comment]
If I use swephR as in import to say ARCHAEOCOSMO, I don;t see the documentation of swephR. I must do something wrong with visibility/environment/export? I see the swephR functions.

**Comment by vreijs** [comment]
On Sat, 24 Nov 2018 at 11:40, Ralf Stubner <notifications@github.com>
> wrote:The problem is that for swe_calc (and swe_fixstar2; also with *ut)
> we already use the function name without swe*. Normally the C++ functions
> use the name without swe_ but get renamed to the name with swe_ at the R
> level. This way we have the normal names at the R level but do not
> interfere with the existing C functions in the C++ files. However, for
> calc and fixstar2 we do not rename the functions for the R level but also
> do not export these functions. Instead we have our own wrapper R functions
> named swe_calc etc., which are used to add some vectorization. I am not
> sure how to solve this best ...
>

I expected soemthing like that, but not sure. Thanks for confirming my
hunch.

> BTW, what is the difference between the vectorization offered in swe_calc
> et al. compared to the one in vec_calc?
>

SO the fact that there are two different vectorisation is thus the cause
that I added this vec_.
As a trial, I now provide as output a list of lists while we earlier
decided to do a data-frame in a list. Depending what is the best way to
present the results, one vectorised (swe_ or vec_) can be removed.
I think my method looks to have cumbersome returns, but I like that *all*
function inputs are based on the same rules as for a data-frame() statement.
In my present use cases (when using excel and SE and ARCHAEOCOSMO) any
input can be vectorised (pending on what I investigate [but I might not be
an average user, but still it is a use case;-).

So perhaps we need to decide which is the best R-like way to do it. As I
know that many roads lead to Rome, any preference?

>

**Comment by rstub** [comment]
I might have found a solution for the API question:

* Most SE functions take only scalar variables as input. One exception are the functions from section6 that get `geopos` as a vector. This is inconsistent with `set_topo()`, so it might make sense to change this in our C++ wrapper. Are there other cases like this?
* Once all functions take scalar values as input, we can vectorize them to take (same length) vectors for all input variables. In C++ we can then loop over these vectors simultaneously.
* Return structure would be a list of (same length) vectors. If the SE function already returns a vector (like `se_calc`), a matrix can be used.

This would be quite close to the SE API but still offer general vectorization without the need of special R wrappers. These can be added if we decide that it is desirable to offer user-level functions for unequal length situations, e.g. one datetime, one set of flags but many planets ....

What do you think?

**Comment by vreijs** [comment]
I will ask SE authors why they use this inconsistency arond the array and
function of  geopos. I think I asked that also a few years ago, but I
forgot if there was a good reason (might be to be consistent with past
functions, but that should not worry us too much. but it might also be
different).
I also removed already any vector input in my vec_ functions, is that much
slower than doing the data-frame concept in C?
Anyway I will ask the background.

All the best,


Victor

**Comment by vreijs** [comment]
>
>    - Most SE functions take only scalar variables as input. One exception
>    are the functions from section6 that get geopos as a vector. This is
>    inconsistent with set_topo(), so it might make sense to change this in
>    our C++ wrapper. Are there other cases like this?
>
> There are a few more functisons that use arrays as input. Look in
vertorisedSEfunctions.R for the variables: geopos, date, dobs, xin,

**Comment by vreijs** [comment]
Hello Ralf,

Here is the feedback from Dieter:
"

> Am Sa., 1. Dez. 2018 um 10:51 Uhr schrieb Victor Reijs <
> web.victor.reijs@gmail.com>:
>
>> Hello Dieter,
>>
>> Is there a reason why you sometimes use the array geopos as input, but in
>> other situations you relay io the setting them through swe_set_topo(). Why
>> is this? Any important reason?
>>
>
> When we first created the function swe_calc() and the like, we did not
> give them a parameter geopos because we did not intend to provide
> topocentric positions yet. A few years later we needed topocentric
> planetary positions. But we did not want to create new versions of the same
> functions (swe_calc, swe_calc_ut, swe_fixstar, swe_fixstar_ut) with a
> parameter geopos. Instead, we chose to create swe_set_topo() which informs
> those functions which geopos it should use. Not necessarily a wise
> decision, but that's why we do it like this.
>
> > Which function really need swe_set_topo(), is that 'only' calc-related
> functions?
>
> Only the above-mentioned ones, I think."


 Due to the semantics of vectors in R, perhaps we should indeed use single
value input parameters (and use the vector for calculating multiple output
scenarios). So that is what I did with my vec_ functions.
You propose to use as output a list of matrices. And perhaps that is better
then my list of lists, as a list of matrices provide a nice results if the
matrix length is 1 (IMHO more consistent than a list of list with length
1).
You also propose to do the multiple input in Rcpp instead of R, I assume
that it is slightly faster in Rcpp.
I though like that we use the 'data_structure' methodology for the input
vectors (so all input parameters can be a vector and the largest vector
length must be integer multiples of all the other input vector lengths)
So I have no issue to use that method. I think that is quite R-like (both
for input and output).

All the best,


Victor

**Comment by vreijs** [comment]
In the above 'data_structure', should be 'data frame' of course.

**Comment by vreijs** [comment]
By the way, using a list of matrices makes determining the number of rows the matrices in the results not easy (length(results) does not show the length of the input vector when using swe_calc.. Example:
> length(swe_calc(c(123568,1234567),0,260))
[1] 3
But perhaps I use a wrong function!

When using vec_calc then length(vec_calc) nicely shows the number of results...
> length(vec_calc(c(123568,1234567),0,260))
[1] 2


Length=2 is correct.
Perhaps I

**Comment by vreijs** [comment]
Sometimes after doing library(swephR) I don't see the help files (like ?Section2). Do I do something wrong with envioronment/global/etc?

**Comment by rstub** [comment]
> Sometimes after doing library(swephR) I don't see the help files (like ?Section2). Do I do something wrong with envioronment/global/etc?

The necessary `@name` tags where missing. My last commit should fix that.

**Comment by vreijs** [comment]
Thanks for rectifying this. Is the @rdname still of importance (beside the
@name)? Or is 'rdname' related to name the rd file, while 'name' makes it
global visible?

**Comment by vreijs** [comment]
I think we could push this to CRAN or not. I know the vectorised is still not agreed, but it would be great to have the present version on CRAN (so we can decide later what to do with the vectorisation). A merry Chrsitmas and a happy 2019!

**Comment by rstub** [comment]
How about pushing a version without the vectorization to CRAN? I could delete all the vectorization functions and right away create a new  branch where I undo that commit.

For now I will just merge this PR, since it has grown way to large anyway.

**Comment by vreijs** [comment]
We can remove the vectorisation by removing two files: 
. one in the R directory: vectorisedSEfunctions.R
. one in the vignette: VectorisedSwephR.Rmd

**Comment by rstub** [comment]
Ok. I have removed these files, made some adjustments in `master` and bumped the version to 0.1.0. then I have created a new branch `vreijs/vectorization`. New work that affects the *vectorization* should go there. Can you open a PR for that?

BTW, we now have a [web page](https://rstub.github.io/swephR/).

**Comment by vreijs** [comment]
Thanks.

**Comment by vreijs** [comment]
What is now the process to put it on CRAN? Let me know.

**Comment by vreijs** [comment]
I don;t know how to open a PR? I thought I did it, but I don't see any 'Pull request' (still at zero).

**Comment by rstub** [comment]
> I don;t know how to open a PR? I thought I did it, but I don't see any 'Pull request' (still at zero).

If you go to <https://github.com/rstub/swephR/branches> you will see a button  to open a PR for that branch.

**Comment by vreijs** [comment]
I managed to do it thanks.

**Pull request merged**
